@baseUrl=http://localhost:3003
@resourceName=notification
@your_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGVkMjE0NTgzOWM0NWQ4NTUzZTkzOCIsImVtYWlsIjoiVGhheUJhbmcxMjNAZ21haWwuY29tIiwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2NzkxOTc3ODgsImV4cCI6MTY3OTI4NDE4OH0.L1M_heJWmCLoqHZu2GbhbDHAOCsHrHZnlZysY1Vjnp8


# Products

# @name getNotificationForTeacher
GET {{baseUrl}}/{{resourceName}}/teachers/641569c23522a2d825e1b60b
x-access-token:{{your_token}}
###

# @name getNotificationForTeacher
GET {{baseUrl}}/{{resourceName}}/students/641579f62dd69c8edd25a17c
x-access-token:{{your_token}}


###

# @name teacher-send-student
POST {{baseUrl}}/{{resourceName}}/teacher
 Authorization: Bearer {{your_token}}
 Content-Type: application/json
{
  "studentId": "641579f62dd69c8edd25a17c",
  "teacherId": "641569c23522a2d825e1b60b",
  "title": " bai tap 3",
  "message": " lenh if else"
}

###

# @name student-send-teacher
POST {{baseUrl}}/{{resourceName}}/student
 Authorization: Bearer {{your_token}}
 Content-Type: application/json
{
  "studentId": "641579f62dd69c8edd25a17c",
  "teacherId": "641569c23522a2d825e1b60b",
  "title": "sinh vien gui",
  "message": " chao thay"
}
###

